# Generated by Django 4.2.7 on 2025-12-20 12:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20, unique=True, verbose_name='代码')),
                ('market', models.CharField(choices=[('US', '美股'), ('CN', 'A股')], max_length=2, verbose_name='市场')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '标的',
                'verbose_name_plural': '标的',
                'db_table': 'instruments',
                'ordering': ['symbol'],
            },
        ),
        migrations.CreateModel(
            name='Candle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('open', models.DecimalField(decimal_places=4, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='开盘价')),
                ('high', models.DecimalField(decimal_places=4, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='最高价')),
                ('low', models.DecimalField(decimal_places=4, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='最低价')),
                ('close', models.DecimalField(decimal_places=4, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='收盘价')),
                ('volume', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='成交量')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(0)], verbose_name='成交额')),
                ('turnover', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='换手率(%)')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candles', to='data_master.instrument', verbose_name='标的')),
            ],
            options={
                'verbose_name': 'K线数据',
                'verbose_name_plural': 'K线数据',
                'db_table': 'candles',
                'ordering': ['instrument', 'date'],
                'indexes': [models.Index(fields=['instrument', 'date'], name='candles_instrum_24418d_idx'), models.Index(fields=['date'], name='candles_date_5dc411_idx')],
                'unique_together': {('instrument', 'date')},
            },
        ),
    ]
