# Generated by Django 4.2.27 on 2025-12-20 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_master', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='行业分类'),
        ),
    ]
