# Generated by Django 4.2.27 on 2025-12-20 13:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_master', '0002_instrument_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandleMinute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(verbose_name='日期时间')),
                ('interval', models.CharField(choices=[('1m', '1分钟'), ('5m', '5分钟'), ('15m', '15分钟'), ('30m', '30分钟'), ('60m', '60分钟')], default='1m', max_length=5, verbose_name='时间间隔')),
                ('open', models.DecimalField(decimal_places=4, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='开盘价')),
                ('high', models.DecimalField(decimal_places=4, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='最高价')),
                ('low', models.DecimalField(decimal_places=4, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='最低价')),
                ('close', models.DecimalField(decimal_places=4, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='收盘价')),
                ('volume', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='成交量')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(0)], verbose_name='成交额')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minute_candles', to='data_master.instrument', verbose_name='标的')),
            ],
            options={
                'verbose_name': '分钟K线数据',
                'verbose_name_plural': '分钟K线数据',
                'db_table': 'candles_minute',
                'ordering': ['instrument', 'datetime'],
                'indexes': [models.Index(fields=['instrument', 'datetime', 'interval'], name='candles_min_instrum_e10f8e_idx'), models.Index(fields=['datetime'], name='candles_min_datetim_ce7e06_idx')],
                'unique_together': {('instrument', 'datetime', 'interval')},
            },
        ),
    ]
