# Generated by Django 4.2.27 on 2025-12-21 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_master', '0003_candleminute'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='trading_rule',
            field=models.CharField(blank=True, choices=[('T+0', 'T+0'), ('T+1', 'T+1')], default='T+1', max_length=3, null=True, verbose_name='交易规则'),
        ),
    ]
