# Generated by Django 4.2.20 on 2025-12-26 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_master', '0004_instrument_trading_rule'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='exchange',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='交易所'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='market',
            field=models.CharField(choices=[('US', '美股'), ('CN', 'A股'), ('CRYPTO', '加密货币')], max_length=10, verbose_name='市场'),
        ),
        migrations.CreateModel(
            name='TradeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy_name', models.CharField(db_index=True, max_length=50, verbose_name='策略名称')),
                ('symbol', models.CharField(db_index=True, max_length=20, verbose_name='代码')),
                ('exchange', models.CharField(blank=True, default='', max_length=20, verbose_name='交易所')),
                ('direction', models.CharField(choices=[('BUY', '买入'), ('SELL', '卖出')], max_length=10, verbose_name='方向')),
                ('order_type', models.CharField(choices=[('MARKET', '市价单'), ('LIMIT', '限价单')], default='MARKET', max_length=10, verbose_name='订单类型')),
                ('price', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='成交价格')),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='成交数量')),
                ('fee', models.DecimalField(decimal_places=8, default=0, max_digits=20, verbose_name='手续费')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='成交时间')),
                ('is_backtest', models.BooleanField(db_index=True, default=False, verbose_name='是否回测')),
                ('backtest_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='回测ID')),
                ('order_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='订单ID')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '交易记录',
                'verbose_name_plural': '交易记录',
                'db_table': 'trade_records',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['strategy_name', 'timestamp'], name='trade_recor_strateg_34718d_idx'), models.Index(fields=['symbol', 'timestamp'], name='trade_recor_symbol_06749b_idx'), models.Index(fields=['is_backtest', 'timestamp'], name='trade_recor_is_back_280869_idx')],
            },
        ),
        migrations.CreateModel(
            name='MarketData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=20, verbose_name='代码')),
                ('exchange', models.CharField(db_index=True, max_length=20, verbose_name='交易所')),
                ('datetime', models.DateTimeField(db_index=True, verbose_name='时间戳')),
                ('open_price', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='开盘价')),
                ('high_price', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='最高价')),
                ('low_price', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='最低价')),
                ('close_price', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='收盘价')),
                ('volume', models.DecimalField(decimal_places=8, max_digits=30, verbose_name='总成交量')),
                ('amount', models.DecimalField(decimal_places=8, max_digits=30, verbose_name='总成交额')),
                ('taker_buy_volume', models.DecimalField(blank=True, decimal_places=8, max_digits=30, null=True, verbose_name='主动买入量')),
                ('volume_direction', models.IntegerField(default=0, help_text='1: 主动买入占优, -1: 主动卖出占优, 0: 中性', verbose_name='成交量方向')),
                ('interval', models.CharField(choices=[('1m', '1分钟'), ('5m', '5分钟'), ('15m', '15分钟'), ('30m', '30分钟'), ('60m', '60分钟'), ('1d', '日线')], default='1m', max_length=10, verbose_name='时间间隔')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '统一行情数据',
                'verbose_name_plural': '统一行情数据',
                'db_table': 'market_data',
                'ordering': ['-datetime'],
                'indexes': [models.Index(fields=['symbol', 'datetime'], name='market_data_symbol_3068fd_idx'), models.Index(fields=['exchange', 'datetime'], name='market_data_exchang_841321_idx'), models.Index(fields=['symbol', 'exchange', 'datetime'], name='market_data_symbol_66b662_idx'), models.Index(fields=['datetime', 'interval'], name='market_data_datetim_56d348_idx')],
                'unique_together': {('symbol', 'exchange', 'datetime', 'interval')},
            },
        ),
    ]
